### ISSUE TITLE
Sensitive Data Exposure

### ISSUE THREAD

**Issue by kylekarpack** [robinpyon/sanity-plugin-dashboard-widget-vercel#2]
It looks like this plugin asks for a Vercel account token, which is then built into the dashboard configuration file. The resulting JS bundle for Sanity Studio at `/static/js/app.bundle.js` is publicly available and contains the token in plain text:

![image](https://user-images.githubusercontent.com/2429580/109432831-f6ba8500-79c1-11eb-80ab-8531b2f75942.png)

Is there a recommended way to implement this that doesn't expose the Vercel token? Or a way to use a token that has lower privileges? Thank you in advance.

**Comment by robinpyon** [comment]
Hey @kylekarpack – I'm afraid it's not possible with the plugin (right now) to hide that account token from showing up in the app payload. (I'll update the README to better highlight this too).

In future it _would_ be possible for the plugin to store that data in a separate Sanity singleton document which the plugin accesses, but that token would still come down the wire and be publicly exposed as well. It'd just be in the response body of an XHR request rather than in the app JS payload. But if such an approach is acceptable to you, then I'd recommend checking out an [alternative Vercel deploy plugin](https://github.com/ndimatteo/sanity-plugin-vercel-deploy) which stores the account token in this way and you could use that right now.

> Is there a recommended way to implement this that doesn't expose the Vercel token? Or a way to use a token that has lower privileges? 

Outside using oauth, I don't believe so. Unfortunately Vercel don't provide scoped access tokens – or tokens scoped to teams either – which is another issue altogether!

**Comment by robinpyon** [comment]
On further thought, storing those credentials in a separate sanity document – whilst still exposed down the wire – at least offers you the ability to prevent access if you're using Sanity's [Access Control Rules](https://www.sanity.io/docs/access-control) on an enterprise plan, so for that reason it makes sense for the plugin to implement it that way

**Comment by kylekarpack** [comment]
Hi @robinpyon, thanks for the clarification. I think that all makes sense. I am using the `sanity-plugin-vercel-deploy` already, and I think that approach (similar to what you mentioned) might make sense here as well. It makes a groq query something like as follows to get data:
```
*[_type == "webhook_deploy"] | order(_createdAt)
```
and that data looks like this:
```json
{
  "ms": 20,
  "query": "*[_type == \"webhook_deploy\"] | order(_createdAt)",
  "result": [
    {
      "name": <DEPLOY_CONFIGURATION_NAME>,
      "url": <WEBHOOK_URL>,
      "vercelProject": <VERCEL_PROJECT_NAME>,
      "vercelTeam": {},
      "vercelToken": <VERCEL_TOKEN>
    }
  ]
}
```
The results of that query aren't available without authentication with Sanity as far as I am aware, so I'm wondering if this might be a better way to store and retrieve the token. I'll create a fork and see if I can come up with a decent implementation that combines the convenience of the dashboard widget with the security of storing the credentials in an access-controlled manner. If I come up with anything good, I'll submit a PR!

I think this probably isn't a huge issue since it's relatively obscure, but that Vercel token does allow for full read/write access to a Vercel account, so accidentally exposing it could definitely be very bad.

**Comment by kylekarpack** [comment]
@robinpyon, I think the note that was added might not quite be correct:

> Your Vercel token is currently bundled in the Sanity studio application payload and exposed to all authenticated studio users

From what I can see, the token is exposed publicly as that bundle file is available anyone who knows where to look. That's what made me think this was a bit more of an issue. Exposing it to authenticated users, while unfortunate, probably isn't nearly as big a deal. 

Example from my Sanity Studio here: https://sb-next-sanity-studio.vercel.app/static/js/app.bundle.js (search for "NOT_A_VALID_TOKEN" to see the secret). I don't think you need any authentication to see this file, which makes it more concerning that it contains a Vercel token.

**Comment by robinpyon** [comment]
You're absolutely right, @kylekarpack – I misunderstood you here, my apologies. This is definitely not ideal at all – I'll look into this very shortly!

**Comment by robinpyon** [comment]
@kylekarpack – again, thanks so much for bringing this to my attention

I've just pushed `1.0.0` which now stores vercel configuration in a namespaced document. There's also support for displaying more than one deployment target.

**Comment by fabien** [comment]
@robinpyon I've been browsing the source code but I could only find a namespaced `_type` which does not prevent those documents from being exposed. I did not see how a document `_id` itself is being namespaced on creation, which makes me wonder if this actually works as you intended it.

For now, I have given up on this plugin and decided to roll my own. Apparently, I wasn't able to enter the correct details when creating a new deployment target. The only token I could find is the one associated with my personal Vercel account (Teams do not have such tokens AFAIK). And for whatever reason, the combination of settings did not add up.

Given that strictly speaking, only the webhook URL is essential to perform a deploy, I wonder why I even need the other settings but I guess it helps to get the realtime updates on the progress?

**Comment by robinpyon** [comment]
Hey @fabien – thank you for bringing this to my attention. Regretfully, you're absolutely right – this is clearly an earlier misunderstanding on my end here. 

Fortunately, it's an easy fix which I should be able to roll out shortly, but understand if you've decided to roll your own.

> The only token I could find is the one associated with my personal Vercel account (Teams do not have such tokens AFAIK)

That's correct – unfortuantely there aren't tokens scoped to teams, which can get a bit awkward if you're working across multiple projects

> Given that strictly speaking, only the webhook URL is essential to perform a deploy, I wonder why I even need the other settings but I guess it helps to get the realtime updates on the progress?

Also correct!
